[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scan-benchmark"
version = "0.1.1"
description = "Surrogate benchmark library"
requires-python = ">=3.10"
dependencies = [
    "xgboost==3.1.3",
    "scikit-learn==1.7.2",
    "tabpfn==6.4.1",
    "matplotlib",
    "seaborn",
    "torch==2.9.1",
    "tqdm"
]

[tool.setuptools.packages.find]
include = [
    "scan_benchmark",
    "scan_benchmark.commons.*",
    "scan_benchmark.vlm",
    "scan_benchmark.vlm.*",
    "scan_benchmark.llm",
    "scan_benchmark.llm.*",
    "scan_benchmark.tabpfn",
    "scan_benchmark.tabpfn.*"
]

exclude = [
    "scan_benchmark.commons.plotting",
    "scan_benchmark.commons.predictors",
    "scan_benchmark.commons.train",
    "scan_benchmark.*.performance_surrogate.results",
    "scan_benchmark.vlm.divergence_surrogate.results",
    "scan_benchmark.*.performance_surrogate.train",
]

[tool.setuptools.package-data]
"scan_benchmark.vlm" = ["*.json"]
"scan_benchmark.vlm.performance_surrogate" = ["splits/*.csv"]
"scan_benchmark.vlm.divergence_surrogate" = ["xgb_models/*.json"]
"scan_benchmark.llm" = ["data/*.csv"]
"scan_benchmark.tabpfn.performance_surrogate" = ["splits/*.csv"]
"scan_benchmark.tabpfn.performance_surrogate" = ["*.json"]
